#!/bin/bash
#
# Name the job sum 
#$ -N helloworld 
#
#$ -cwd
#
# Join STDOUT and STDERR
#$ -j y
#
# Request the mpi parallel environment and 2 slots
#$ -pe mpi 2

# Load the environment modules
source /usr/share/Modules/init/bash

# Load the module for MPI
module load mvapich2-2.0/gcc-4.7.2

# Run the mpi job
/act/mvapich2-2.0/gcc-4.7.2/bin/mpiexec -np $NSLOTS python /home/hofer/mpi-vina/py_src/src/mpiVINA.py
